#!/usr/bin/env python3
"""Generate dbuf_dispatch.inc (kernel dispatch table) and the sweep list.

Single source of truth for the warptile_dbuf autotune space. The generated
dispatch covers every VALID config in the space; sweep_dbuf.py reads the same
space from here (via --list) so the sweep never tests a config the binary
can't launch.
"""
import itertools

BM_SET = [64, 128, 256]
BN_SET = [64, 128, 256]
BK_SET = [8, 16, 32]
WM_SET = [32, 64, 128]
WN_SET = [32, 64, 128]
WNITER_SET = [1, 2]
TM_SET = [4, 8]
TN_SET = [4, 8]

SMEM_LIMIT = 228 * 1024  # H100 bytes per SM


def valid(cfg):
    BM, BN, BK, WM, WN, WNITER, TM, TN = cfg
    NT = (BM // WM) * (BN // WN) * 32
    WMITER = (WM * WN) // (32 * TM * TN * WNITER)
    # exact tiling constraints
    if BM % WM or BN % WN or WN % WNITER:
        return None
    WMITER_exact = (WM * WN) == 32 * TM * TN * WMITER * WNITER
    if not WMITER_exact:
        return None
    if WMITER <= 0 or WM % WMITER:
        return None
    WSUBM = WM // WMITER
    WSUBN = WN // WNITER
    if WSUBM % TM or WSUBN % TN:
        return None
    if 32 % (WSUBN // TN):
        return None
    if NT > 1024 or NT < 32:
        return None
    smem = 2 * (BM * BK + BK * BN) * 4
    if smem > SMEM_LIMIT:
        return None
    return (BM, BN, BK, WM, WN, WNITER, TM, TN, NT)


def all_configs():
    seen = set()
    out = []
    for cfg in itertools.product(BM_SET, BN_SET, BK_SET, WM_SET, WN_SET,
                                 WNITER_SET, TM_SET, TN_SET):
        v = valid(cfg)
        if v is None or v in seen:
            continue
        seen.add(v)
        out.append(v)
    return out


def emit_dispatch(configs):
    lines = []
    for (BM, BN, BK, WM, WN, WNITER, TM, TN, NT) in configs:
        lines.append(
            f"    if (BM=={BM} && BN=={BN} && BK=={BK} && WM=={WM} && WN=={WN} && "
            f"WNITER=={WNITER} && TM=={TM} && TN=={TN} && NUM_THREADS=={NT})\n"
            f"        matmulWarptileDbufKernelT<{BM}, {BN}, {BK}, {WM}, {WN}, "
            f"{WNITER}, {TM}, {TN}, {NT}><<<blocks, threads>>>(d_A, d_B, d_C, N);"
        )
    return "\n".join(lines)


if __name__ == "__main__":
    import sys
    configs = all_configs()
    if "--list" in sys.argv:
        for c in configs:
            print(",".join(map(str, c)))
        print(f"# total {len(configs)} valid configs", file=sys.stderr)
    else:
        with open("matmul/dbuf_dispatch.inc", "w") as f:
            f.write("// GENERATED by scripts/gen_dbuf_dispatch.py — DO NOT EDIT\n")
            f.write(emit_dispatch(configs))
            f.write("\n")
        print(f"wrote matmul/dbuf_dispatch.inc with {len(configs)} configs")
