#!/usr/bin/env python3
"""Generate dispatch + config table for the 1D blocktile autotune space.

Single source of truth for the 1D config space. Constraints (from the
original kernel's structure):
  - BM = BN = BK * TM   (1D thread mapping: one thread column spans BK tile)
  - threads = BN * BM / TM <= 1024
  - BK in {2, 4, 8, 16}; TM in {4..256} (power-of-2 steps)
Emit: matmul_1d_dispatch.inc (kernel dispatch), matmul_1d_launch.inc
(dispatch body used inside launch1DTuned), plus prints the config list.
"""

import itertools

BKS = [2, 4, 8, 16]
TMS = [4, 8, 16, 32, 64, 128, 256]

configs = []
for bk, tm in itertools.product(BKS, TMS):
    bn = bk * tm
    bm = bn
    threads = bn * bm // tm  # = bk*bk*tm
    if threads > 1024:
        continue
    # skip degenerate: BK*TM must give sensible tile (>=32)
    if bn < 32:
        continue
    configs.append((bm, bn, bk, tm))

# dedupe & sort deterministically
configs = sorted(set(configs))

print(f"# {len(configs)} valid 1D configs")
for bm, bn, bk, tm in configs:
    print(f"# BM={bm} BN={bn} BK={bk} TM={tm} threads={bn*bm//tm}")

with open("matmul/matmul_1d_dispatch.inc", "w") as f:
    f.write("// GENERATED by scripts/gen_1d_dispatch.py — do not edit.\n")
    f.write(f"static const int NUM_1D_CONFIGS = {len(configs)};\n")
    f.write("struct Cfg1D { int BM, BN, BK, TM; };\n")
    f.write("static const Cfg1D kConfigs1D[] = {\n")
    for bm, bn, bk, tm in configs:
        f.write(f"    {{{bm}, {bn}, {bk}, {tm}}},\n")
    f.write("};\n\n")
    f.write("// kernel dispatch: one branch per config\n")
    for bm, bn, bk, tm in configs:
        f.write(
            f"template __global__ void matmul1DTunedKernel<Traits, {bm}, {bn}, {bk}, {tm}>("
            f"const typename Traits::T*, const typename Traits::T*, float*, int);\n"
        )

with open("matmul/matmul_1d_launch.inc", "w") as f:
    f.write("// GENERATED by scripts/gen_1d_dispatch.py — do not edit.\n")
    for bm, bn, bk, tm in configs:
        f.write(f"    if (BM == {bm} && BN == {bn} && BK == {bk} && TM == {tm}) {{\n")
        f.write(
            f"        dim3 threads({bn * bm // tm});\n"
            f"        dim3 blocks((N + {bn} - 1) / {bn}, (N + {bm} - 1) / {bm});\n"
            f"        matmul1DTunedKernel<Traits, {bm}, {bn}, {bk}, {tm}>"
            f"<<<blocks, threads>>>(A, B, C, N);\n"
            f"        cudaCheckError(cudaGetLastError());\n"
            f"        return true;\n"
            f"    }}\n")
print("wrote matmul/matmul_1d_dispatch.inc + matmul/matmul_1d_launch.inc")
