#!/usr/bin/env python3
"""Generate matmul_warptile_configs.inc — pruned warptile autotune space.

Source of truth: archive-cudakernels CANDIDATES_W (479 machine-generated
candidates, BM/BN/BK/TM/TN/WM/WN). The full space costs ~50 min per dtype to
sweep; we prune with FP16 priors established by the 1D/2D/vec autotunes
(2026-09-26/27):

  - FP16 optima so far always sit at BK=8 (shallow K tile; SMEM bytes halved)
    while FP32 optima sit at BK=16 — keep both BK values.
  - FP16 collapses at TM=4 configs and wins at TM=16 — drop TM=4, keep 8/16.
  - WN=128 / WM=128 (huge warp tiles) never appeared in any top-10 — drop.

The FP32 warptile winner (128,128,16,16,4,64,32) survives every filter
(regression anchor).

Emits: kConfigsW[] table + launch dispatch branches, mirroring the
matmul_1d_launch.inc pattern.
"""

import re
import os

ARCHIVE = os.path.expanduser("~/code/archive-cudakernels/matmul/matmul_warptile.cu")
OUT = os.path.join(os.path.dirname(__file__), "..", "matmul", "matmul_warptile_configs.inc")

s = open(ARCHIVE).read()
m = re.search(r"CANDIDATES_W\[\] = \{(.*?)\};", s, re.S)
rows = [tuple(int(x) for x in r) for r in
        re.findall(r"\{(\d+), (\d+), (\d+), (\d+), (\d+), (\d+), (\d+)\}", m.group(1))]
assert len(rows) == 479, f"expected 479 archive candidates, got {len(rows)}"

def keep(c):
    BM, BN, BK, TM, TN, WM, WN = c
    if BK not in (8, 16): return False       # FP16 prior: shallow/deep both live
    if TM not in (8, 16): return False       # FP16 prior: TM=4 never competitive
    if WN == 128 or WM == 128: return False  # huge warp tiles never in top-10
    # validity (same as archive): warp splits exact, thread tiles >= 1
    if BM % WM or BN % WN: return False
    if WM % (4 * TM) or WN % (8 * TN): return False
    threads = (BM // WM) * (BN // WN) * 32
    if threads > 1024: return False
    return True

sel = [c for c in rows if keep(c)]
# dedupe, stable order
seen = set(); cfgs = []
for c in sel:
    if c not in seen:
        seen.add(c); cfgs.append(c)

anchor = (128, 128, 16, 16, 4, 64, 32)
assert anchor in cfgs, "FP32 winner (regression anchor) must survive pruning!"

lines = []
lines.append("// GENERATED by scripts/gen_warptile_dispatch.py — DO NOT EDIT")
lines.append(f"// Pruned from archive CANDIDATES_W ({len(rows)} candidates) with FP16 priors:")
lines.append("//   BK in {{8,16}}, TM in {{8,16}}, WM/WN != 128, valid warp geometry")
lines.append(f"// -> {len(cfgs)} configs. FP32 winner (128,128,16,16,4,64,32) retained.")
lines.append("")
lines.append("struct CfgWEnum { int BM, BN, BK, TM, TN, WM, WN; };")
lines.append("static const CfgWEnum kConfigsW[] = {")
for c in cfgs:
    lines.append("    {%d, %d, %d, %d, %d, %d, %d}," % c)
lines.append("};")
lines.append("static const int NUM_W_CONFIGS = sizeof(kConfigsW) / sizeof(kConfigsW[0]);")
lines.append("")
lines.append("// Launch dispatch (order matches kConfigsW[])")
lines.append("// LW(BM,BN,BK,TM,TN,WM,WN)")
lines.append("#define LW(_BM,_BN,_BK,_TM,_TN,_WM,_WN) \\")
lines.append("    if (BM == _BM && BN == _BN && BK == _BK && TM == _TM && TN == _TN && WM == _WM && WN == _WN) { \\")
lines.append("        matmulWarptileTunedKernel<Traits, _BM, _BN, _BK, _TM, _TN, _WM, _WN><<<grid, threads>>>(A, B, C, N); \\")
lines.append("        return true; \\")
lines.append("    }")
for c in cfgs:
    lines.append("LW(%d,%d,%d,%d,%d,%d,%d)" % c)
lines.append("#undef LW")

open(OUT, "w").write("\n".join(lines) + "\n")
print(f"wrote {OUT}: {len(cfgs)} configs (pruned from {len(rows)})")
