#!/usr/bin/env python3
"""Generate config table + launch dispatch for the 1D blocktile autotune space.

Constraints (from the original kernel's structure):
  - BM = BN = BK * TM   (1D thread mapping: one thread column spans BK tile)
  - threads = BN * BM / TM <= 1024
  - BK in {2, 4, 8, 16}; TM in {4..256} (power-of-2 steps)

Emits:
  matmul/matmul_1d_configs.inc  — kConfigs1D[] + NUM_1D_CONFIGS (included once,
                                  in the .cu; Cfg1D struct lives in the header)
  matmul/matmul_1d_launch.inc   — dispatch body included INSIDE
                                  launch1DTuned<Traits> (uses its Traits param;
                                  kernels instantiate implicitly)

NOTE: no explicit-instantiation .inc — unlike dbuf (concrete types), the
dtype-templated kernel can't be explicitly instantiated with `Traits` at file
scope. Implicit instantiation through launch1DTuned<Traits> covers it.
"""

import itertools

BKS = [2, 4, 8, 16]
TMS = [4, 8, 16, 32, 64, 128, 256]

configs = []
for bk, tm in itertools.product(BKS, TMS):
    bn = bk * tm
    bm = bn
    threads = bn * bm // tm  # = bk*bk*tm
    if threads > 1024:
        continue
    if bn < 32:
        continue
    configs.append((bm, bn, bk, tm))

configs = sorted(set(configs))
print(f"# {len(configs)} valid 1D configs")

with open("matmul/matmul_1d_configs.inc", "w") as f:
    f.write("// GENERATED by scripts/gen_1d_dispatch.py — do not edit.\n")
    f.write(f"extern const int NUM_1D_CONFIGS = {len(configs)};\n")
    f.write("extern const Cfg1D kConfigs1D[] = {\n")
    for bm, bn, bk, tm in configs:
        f.write(f"    {{{bm}, {bn}, {bk}, {tm}}},\n")
    f.write("};\n")

with open("matmul/matmul_1d_launch.inc", "w") as f:
    f.write("// GENERATED by scripts/gen_1d_dispatch.py — do not edit.\n")
    for bm, bn, bk, tm in configs:
        f.write(f"    if (BM == {bm} && BN == {bn} && BK == {bk} && TM == {tm}) {{\n")
        f.write(
            f"        dim3 threads({bn * bm // tm});\n"
            f"        dim3 blocks((N + {bn} - 1) / {bn}, (N + {bm} - 1) / {bm});\n"
            f"        matmul1DTunedKernel<Traits, {bm}, {bn}, {bk}, {tm}>"
            f"<<<blocks, threads>>>(A, B, C, N);\n"
            f"        cudaError_t err = cudaGetLastError();\n"
            f"        if (err != cudaSuccess) return false;  // launch-infeasible (e.g. register pressure), not fatal\n"
            f"        return true;\n"
            f"    }}\n")
print("wrote matmul_1d_configs.inc + matmul_1d_launch.inc")
